# Generated by Django 5.1.2 on 2025-01-31 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_1', '0003_preload_meetings'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='status',
            field=models.CharField(choices=[('scheduled', 'scheduled'), ('confirmed', 'Confirmed'), ('rescheduled', 'Rescheduled'), ('canceled', 'Canceled')], default='scheduled', max_length=20),
        ),
    ]
